version: "3.9"
services:
  develop:
    image: ${IMAGE_NAME}
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONWARNINGS=ignore # not good, but many warnings during pytest execution
