version: "3.9"
services:
  develop:
    image: gcr.io/fb-mle-march-21/golubitsky/ml-model-deployment:v1
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONWARNINGS=ignore # not good, but many warnings during pytest execution
